"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-09 01:15:50.762047

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Вручную: тип vector нужен до создания таблицы chunks
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authors",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("affiliation", sa.String(length=500), nullable=True),
        sa.Column("orcid", sa.CHAR(length=19), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_authors")),
        sa.UniqueConstraint("orcid", name=op.f("uq_authors_orcid")),
    )
    op.create_index("ix_authors_full_name", "authors", ["full_name"], unique=False)
    op.create_table(
        "keywords",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("value", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_keywords")),
        sa.UniqueConstraint("value", name=op.f("uq_keywords_value")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("researcher", "admin", name="user_role"),
            server_default="researcher",
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "issues",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("year", sa.SmallInteger(), nullable=False),
        sa.Column("volume", sa.SmallInteger(), nullable=True),
        sa.Column("number", sa.SmallInteger(), nullable=False),
        sa.Column("scan_path", sa.Text(), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "created",
                "uploaded",
                "ocr_in_progress",
                "ocr_done",
                "indexed",
                "failed",
                name="issue_status",
            ),
            server_default="created",
            nullable=False,
        ),
        sa.Column("created_by", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("page_count > 0", name=op.f("ck_issues_page_count_positive")),
        sa.CheckConstraint("year >= 1987", name=op.f("ck_issues_year_min")),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_issues_created_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_issues")),
        sa.UniqueConstraint("year", "number", name=op.f("uq_issues_year_number")),
    )
    op.create_table(
        "articles",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("issue_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("abstract", sa.Text(), nullable=True),
        sa.Column("doi", sa.String(length=100), nullable=True),
        sa.Column("language", sa.CHAR(length=2), server_default="ru", nullable=False),
        sa.Column("page_start", sa.Integer(), nullable=False),
        sa.Column("page_end", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("page_start <= page_end", name=op.f("ck_articles_page_range")),
        sa.ForeignKeyConstraint(
            ["issue_id"],
            ["issues.id"],
            name=op.f("fk_articles_issue_id_issues"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_articles")),
        sa.UniqueConstraint("doi", name=op.f("uq_articles_doi")),
    )
    op.create_index(
        "ix_articles_issue_pages", "articles", ["issue_id", "page_start", "page_end"], unique=False
    )
    op.create_table(
        "ocr_jobs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("issue_id", sa.BigInteger(), nullable=False),
        sa.Column("requested_by", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("queued", "running", "done", "failed", name="job_status"),
            server_default="queued",
            nullable=False,
        ),
        sa.Column("pages_total", sa.Integer(), nullable=True),
        sa.Column("pages_done", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["issue_id"],
            ["issues.id"],
            name=op.f("fk_ocr_jobs_issue_id_issues"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"], ["users.id"], name=op.f("fk_ocr_jobs_requested_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ocr_jobs")),
    )
    op.create_index(
        "ux_ocr_jobs_active",
        "ocr_jobs",
        ["issue_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )
    op.create_table(
        "pages",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("issue_id", sa.BigInteger(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("text_md", sa.Text(), nullable=True),
        sa.Column("ocr_model", sa.String(length=100), nullable=True),
        sa.Column("recognized_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("page_number > 0", name=op.f("ck_pages_page_number_positive")),
        sa.ForeignKeyConstraint(
            ["issue_id"], ["issues.id"], name=op.f("fk_pages_issue_id_issues"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pages")),
        sa.UniqueConstraint("issue_id", "page_number", name=op.f("uq_pages_issue_id_page_number")),
    )
    op.create_table(
        "article_authors",
        sa.Column("article_id", sa.BigInteger(), nullable=False),
        sa.Column("author_id", sa.BigInteger(), nullable=False),
        sa.Column("author_order", sa.SmallInteger(), nullable=False),
        sa.CheckConstraint(
            "author_order > 0", name=op.f("ck_article_authors_author_order_positive")
        ),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
            name=op.f("fk_article_authors_article_id_articles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["authors.id"],
            name=op.f("fk_article_authors_author_id_authors"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("article_id", "author_id", name=op.f("pk_article_authors")),
    )
    op.create_table(
        "article_keywords",
        sa.Column("article_id", sa.BigInteger(), nullable=False),
        sa.Column("keyword_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
            name=op.f("fk_article_keywords_article_id_articles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["keyword_id"],
            ["keywords.id"],
            name=op.f("fk_article_keywords_keyword_id_keywords"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("article_id", "keyword_id", name=op.f("pk_article_keywords")),
    )
    op.create_table(
        "chunks",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("page_id", sa.BigInteger(), nullable=False),
        sa.Column("chunk_index", sa.SmallInteger(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
        sa.ForeignKeyConstraint(
            ["page_id"], ["pages.id"], name=op.f("fk_chunks_page_id_pages"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chunks")),
        sa.UniqueConstraint("page_id", "chunk_index", name=op.f("uq_chunks_page_id_chunk_index")),
    )
    op.create_index(
        "ix_chunks_embedding",
        "chunks",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_chunks_embedding",
        table_name="chunks",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("chunks")
    op.drop_table("article_keywords")
    op.drop_table("article_authors")
    op.drop_table("pages")
    op.drop_index(
        "ux_ocr_jobs_active",
        table_name="ocr_jobs",
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )
    op.drop_table("ocr_jobs")
    op.drop_index("ix_articles_issue_pages", table_name="articles")
    op.drop_table("articles")
    op.drop_table("issues")
    op.drop_table("users")
    op.drop_table("keywords")
    op.drop_index("ix_authors_full_name", table_name="authors")
    op.drop_table("authors")
    # ### end Alembic commands ###
    # Вручную: autogenerate не удаляет ENUM-типы, созданные вместе с таблицами
    for enum_name in ("job_status", "issue_status", "user_role"):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
